version: 2.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout
      - run: npm install
      - run: npm run compile-grammar

  test:
    docker:
      - image: circleci/node:10.16.0

    steps:
      - checkout
      - run: npm install
      - run: npm test
# Now that I have workflows, the default job of "build" shouldn't auto-trigger
workflows:
  build-and-test:
    jobs:
      - build
      - test:
        requires:
          - build
